# Makefile
# See https://docs.cocotb.org/en/stable/quickstart.html for more info

# defaults
SIM ?= icarus
TOPLEVEL_LANG ?= verilog
SRC_DIR = $(PWD)/../src
PROJECT_SOURCES = tt_um_digital_clock_example.v \
  clock_wrapper.v \
  input/refclk_sync.v \
  input/clk_gen.v \
  input/button_debounce.v \
  core/clock_register.v \
  core/clock_mode_converter.v \
  core/decimal_point_controller.v \
  core/display_controller.v \
  core/output_wrapper.v \
  output/clock_to_bcd.v \
  output/binary_to_bcd.v \
  output/max7219_settings.v \
  output/max7219.v \
  test/bcd_to_7seg.v \
  test/test_max7219_moc.v \
  test/test_7seg_to_bcd.v

ifneq ($(GATES),yes)

# RTL simulation:
SIM_BUILD				= sim_build/rtl
VERILOG_SOURCES += $(addprefix $(SRC_DIR)/,$(PROJECT_SOURCES))
COMPILE_ARGS += -I$(SRC_DIR)

else

# Gate level simulation:
SIM_BUILD        = sim_build/gl
COMPILE_ARGS    += -DGL_TEST
COMPILE_ARGS    += -DFUNCTIONAL
COMPILE_ARGS    += -DSIM
VERILOG_SOURCES += $(PDK_ROOT)/ihp-sg13g2/libs.ref/sg13g2_io/verilog/sg13g2_io.v
VERILOG_SOURCES += $(PDK_ROOT)/ihp-sg13g2/libs.ref/sg13g2_stdcell/verilog/sg13g2_stdcell.v

# this gets copied in by the GDS action workflow
VERILOG_SOURCES += $(PWD)/gate_level_netlist.v

# this gets copied in by the GDS action workflow
VERILOG_SOURCES += $(PWD)/gate_level_netlist.v
VERILOG_SOURCES += $(SRC_DIR)/input/refclk_sync.v
VERILOG_SOURCES += $(SRC_DIR)/input/clk_gen.v
VERILOG_SOURCES += $(SRC_DIR)/test/bcd_to_7seg.v
VERILOG_SOURCES += $(SRC_DIR)/test/test_max7219_moc.v
VERILOG_SOURCES += $(SRC_DIR)/test/test_7seg_to_bcd.v
endif

# Include the testbench sources:
VERILOG_SOURCES += $(PWD)/tiny_tapeout_tb.v
TOPLEVEL = tiny_tapeout_tb

# MODULE is the basename of the Python test file
MODULE = test

# include cocotb's make rules to take care of the simulator setup
include $(shell cocotb-config --makefiles)/Makefile.sim
